apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-hub-flapi-backend-cert
  namespace: dev-hub-flapi-backend
spec:
  secretName: dev-hub-flapi-backend-tls
  dnsNames:
    - dev.hub.flapi.api.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
