name: build_deploy_cluster_production

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image - Production version latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/production/Dockerfile
          push: true
          tags: corentin35/hub-flapi-backend:latest
          build-args: |
            DB_USER=${{ secrets.O2SWITCH_DATABASE_USERNAME }}
            DB_PASSWORD=${{ secrets.O2SWITCH_DATABASE_PASSWORD }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            O2SWITCH_API_TOKEN=${{ secrets.O2SWITCH_API_TOKEN }}
            O2SWITCH_DATABASE_USERNAME=${{ secrets.O2SWITCH_DATABASE_USERNAME }}
            O2SWITCH_DATABASE_PASSWORD=${{ secrets.O2SWITCH_DATABASE_PASSWORD }}
            GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.PAT_TOKEN }}
            MAILJET_API_SECRET_KEY=${{ secrets.MAILJET_API_SECRET_KEY }}
            MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}

      - name: Build and push Docker image - Production version x.x.x
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/production/Dockerfile
          push: true
          tags: corentin35/hub-flapi-backend:${{ steps.previoustag.outputs.tag }}
          build-args: |
            DB_USER=${{ secrets.O2SWITCH_DATABASE_USERNAME }}
            DB_PASSWORD=${{ secrets.O2SWITCH_DATABASE_PASSWORD }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            O2SWITCH_API_TOKEN=${{ secrets.O2SWITCH_API_TOKEN }}
            O2SWITCH_DATABASE_USERNAME=${{ secrets.O2SWITCH_DATABASE_USERNAME }}
            O2SWITCH_DATABASE_PASSWORD=${{ secrets.O2SWITCH_DATABASE_PASSWORD }}
            GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.PAT_TOKEN }}
            MAILJET_API_SECRET_KEY=${{ secrets.MAILJET_API_SECRET_KEY }}
            MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ steps.previoustag.outputs.tag }}'/g' k8s/production/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/production/namespace.yaml 
            -f k8s/production/certificate.yaml 
            -f k8s/production/docker-registry-secret.yaml 
            -f k8s/production/deployment.yaml 
            -f k8s/production/hpa.yaml 
            -f k8s/production/ingress.yaml 
            -f k8s/production/service.yaml
